export const NOTAS_CORTE = [
  { curso:"Medicina",               uni:"USP (SP)",     nota:88.4, vagas:150, cor:"#003366", site:"https://fuvest.br"          },
  { curso:"Medicina",               uni:"UNICAMP (SP)", nota:87.3, vagas:80,  cor:"#004d2c", site:"https://comvest.unicamp.br" },
  { curso:"Medicina",               uni:"UNESP (SP)",   nota:84.1, vagas:160, cor:"#8B0000", site:"https://vunesp.com.br"      },
  { curso:"Medicina",               uni:"UNIFESP (SP)", nota:89.1, vagas:80,  cor:"#4B0082", site:"https://unifesp.br"         },
  { curso:"Direito",                uni:"USP (SP)",     nota:79.2, vagas:240, cor:"#003366", site:"https://fuvest.br"          },
  { curso:"Engenharia Civil",       uni:"USP (SP)",     nota:73.5, vagas:180, cor:"#003366", site:"https://fuvest.br"          },
  { curso:"Ciências da Computação", uni:"UNICAMP (SP)", nota:74.8, vagas:120, cor:"#004d2c", site:"https://comvest.unicamp.br" },
  { curso:"Engenharia de Computação",uni:"UNICAMP (SP)",nota:72.1, vagas:100, cor:"#004d2c", site:"https://comvest.unicamp.br" },
  { curso:"Odontologia",            uni:"USP (SP)",     nota:76.3, vagas:100, cor:"#003366", site:"https://fuvest.br"          },
  { curso:"Psicologia",             uni:"USP (SP)",     nota:71.8, vagas:80,  cor:"#003366", site:"https://fuvest.br"          },
  { curso:"Arquitetura",            uni:"USP (SP)",     nota:74.2, vagas:60,  cor:"#003366", site:"https://fuvest.br"          },
  { curso:"Farmácia",               uni:"UNIFESP (SP)", nota:68.4, vagas:80,  cor:"#4B0082", site:"https://unifesp.br"         },
  { curso:"Administração",          uni:"USP (SP)",     nota:66.1, vagas:240, cor:"#003366", site:"https://fuvest.br"          },
  { curso:"Agronomia",              uni:"UNESP (SP)",   nota:61.2, vagas:80,  cor:"#8B0000", site:"https://vunesp.com.br"      },
];